In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

class StudentSalesAnalyze:
    def __init__(self):
        self.df = None
        self.last_plot = None

    def load_dataset(self):
        path = input("Enter CSV file path: ")
        try:
            self.df = pd.read_csv(path)
            print("Dataset loaded successfully!")
            display(self.df.head())
        except Exception as e:
            print("Error:", e)

    def explore_data(self):
        if self.df is None:
            print("Load dataset first.")
            return

        while True:
            print("\n1. First 5 rows\n2. Last 5 rows\n3. Column names")
            print("4. Data types\n5. Basic information\n6. Back")
            ch = input("Enter choice: ")

            if ch == "1":
                display(self.df.head())
            elif ch == "2":
                display(self.df.tail())
            elif ch == "3":
                print(list(self.df.columns))
            elif ch == "4":
                print(self.df.dtypes)
            elif ch == "5":
                self.df.info()
            elif ch == "6":
                break
            else:
                print("Invalid choice!")

    def handle_missing_data(self):
        if self.df is None:
            print("Load dataset first.")
            return

        while True:
            print("\n1. Show missing rows\n2. Fill with mean")
            print("3. Drop missing rows\n4. Replace missing values")
            print("5. Back")
            ch = input("Enter choice: ")

            if ch == "1":
                display(self.df[self.df.isnull().any(axis=1)])
            elif ch == "2":
                self.df.fillna(self.df.mean(numeric_only=True), inplace=True)
                print("Missing numeric values filled.")
            elif ch == "3":
                self.df.dropna(inplace=True)
                print("Missing rows removed.")
            elif ch == "4":
                value = input("Enter replacement value: ")
                try:
                    value = float(value)
                except ValueError:
                    pass
                self.df.fillna(value, inplace=True)
                print("Values replaced.")
            elif ch == "5":
                break
            else:
                print("Invalid choice!")

    def numeric_analysis(self):
        if self.df is None:
            print("Load dataset first.")
            return

        print("Numeric columns:", list(self.df.select_dtypes(include=np.number).columns))
        col = input("Enter numeric column: ")

        if col in self.df.columns and pd.api.types.is_numeric_dtype(self.df[col]):
            arr = self.df[col].dropna().to_numpy()
            if len(arr) == 0:
                print("No numeric data available.")
                return
            print("Array:", arr)
            print("Total:", np.sum(arr))
            print("Average:", np.mean(arr))
            print("Highest:", np.max(arr))
            print("Lowest:", np.min(arr))
        else:
            print("Invalid numeric column!")

    def dataframe_operations(self):
        if self.df is None:
            print("Load dataset first.")
            return

        while True:
            print("\n1. Merge CSV\n2. Split dataset\n3. Back")
            ch = input("Enter choice: ")

            if ch == "1":
                try:
                    path = input("Enter second CSV path: ")
                    df2 = pd.read_csv(path)
                    merged = pd.concat([self.df, df2], ignore_index=True)
                    display(merged.head())
                    if input("Save merged CSV? (yes/no): ").lower() == "yes":
                        merged.to_csv("merged_dataset.csv", index=False)
                        print("Saved as merged_dataset.csv")
                except Exception as e:
                    print("Error:", e)
            elif ch == "2":
                mid = len(self.df) // 2
                print("Part 1:")
                display(self.df.iloc[:mid])
                print("Part 2:")
                display(self.df.iloc[mid:])
            elif ch == "3":
                break
            else:
                print("Invalid choice!")

    def descriptive_stats(self):
        if self.df is None:
            print("Load dataset first.")
            return

        print("Descriptive Statistics:")
        display(self.df.describe())
        print("Standard Deviation:")
        display(self.df.std(numeric_only=True))
        print("Variance:")
        display(self.df.var(numeric_only=True))

    def visualize_data(self):
        if self.df is None:
            print("Load dataset first.")
            return

        while True:
            print("\n1. Bar Chart\n2. Line Chart\n3. Scatter Plot")
            print("4. Sales Pie Chart\n5. Heatmap\n6. Histogram")
            print("7. Stack Plot\n8. Back")
            ch = input("Enter choice: ")

            if ch == "8":
                break

            try:
                if ch == "1":
                    x = input("Enter category column: ")
                    y = input("Enter numeric column: ")
                    fig, ax = plt.subplots()
                    ax.bar(self.df[x], self.df[y])
                    ax.set_title("Bar Chart")

                elif ch == "2":
                    y = input("Enter numeric column: ")
                    fig, ax = plt.subplots()
                    ax.plot(self.df[y])
                    ax.set_title("Line Chart")

                elif ch == "3":
                    x = input("Enter X numeric column: ")
                    y = input("Enter Y numeric column: ")
                    fig, ax = plt.subplots()
                    ax.scatter(self.df[x], self.df[y])
                    ax.set_title("Scatter Plot")

                elif ch == "4":
                    category = input("Enter category column: ")
                    value = input("Enter numeric column: ")
                    data = self.df.groupby(category)[value].sum()
                    fig, ax = plt.subplots()
                    data.plot.pie(autopct="%1.1f%%", ax=ax)
                    ax.set_ylabel("")
                    ax.set_title("Sales Distribution")

                elif ch == "5":
                    fig, ax = plt.subplots()
                    sns.heatmap(self.df.corr(numeric_only=True),
                                annot=True, ax=ax)
                    ax.set_title("Correlation Heatmap")

                elif ch == "6":
                    col = input("Enter numeric column: ")
                    fig, ax = plt.subplots()
                    ax.hist(self.df[col].dropna(), bins=6)
                    ax.set_title("Histogram")

                elif ch == "7":
                    col = input("Enter numeric column: ")
                    fig, ax = plt.subplots()
                    ax.stackplot(self.df.index, self.df[col].fillna(0))
                    ax.set_title("Stack Plot")

                else:
                    print("Invalid choice!")
                    continue

                plt.tight_layout()
                self.last_plot = fig
                plt.show()

            except Exception as e:
                plt.close("all")
                print("Chart error:", e)

    def save_visualization(self):
        if self.last_plot is None:
            print("Create a chart first.")
            return

        name = input("Enter filename (example: chart.png): ")
        if not name.lower().endswith((".png", ".jpg", ".jpeg", ".pdf")):
            name += ".png"

        try:
            self.last_plot.savefig(name, bbox_inches="tight")
            print("Chart saved successfully!")
        except Exception as e:
            print("Error:", e)

analyzer = StudentSalesAnalyze()

while True:
    print("\n===== DATA ANALYSIS & VISUALIZATION PROGRAM =====")
    print("1. Load Dataset")
    print("2. Explore Data")
    print("3. DataFrame Operations")
    print("4. Handle Missing Data")
    print("5. Descriptive Statistics")
    print("6. Data Visualization")
    print("7. Save Visualization")
    print("8. NumPy Numeric Analysis")
    print("9. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        analyzer.load_dataset()
    elif choice == "2":
        analyzer.explore_data()
    elif choice == "3":
        analyzer.dataframe_operations()
    elif choice == "4":
        analyzer.handle_missing_data()
    elif choice == "5":
        analyzer.descriptive_stats()
    elif choice == "6":
        analyzer.visualize_data()
    elif choice == "7":
        analyzer.save_visualization()
    elif choice == "8":
        analyzer.numeric_analysis()
    elif choice == "9":
        print("Thank you! Program ended.")
        break
    else:
        print("Invalid choice. Try again.")

===== DATA ANALYSIS & VISUALIZATION PROGRAM =====
1. Load Dataset
2. Explore Data
3. DataFrame Operations
4. Handle Missing Data
5. Descriptive Statistics
6. Data Visualization
7. Save Visualization
8. NumPy Numeric Analysis
9. Exit

Enter your choice:  1
Enter CSV file path:  sample_data.csv

Dataset loaded successfully!

   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago

===== DATA ANALYSIS & VISUALIZATION PROGRAM =====
1. Load Dataset
2. Explore Data
3. DataFrame Operations
4. Handle Missing Data
5. Descriptive Statistics
6. Data Visualization
7. Save Visualization
8. NumPy Numeric Analysis
9. Exit

Enter your choice:  2

1. First 5 rows
2. Last 5 rows
3. Column names
4. Data types
5. Basic information
6. Back

Enter choice:  2

   id     name  age         city
0   1    Alice   25     New York
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago

1. First 5 rows
2. Last 5 rows
3. Column names
4. Data types
5. Basic information
6. Back

Enter choice:  6

===== DATA ANALYSIS & VISUALIZATION PROGRAM =====
1. Load Dataset
2. Explore Data
3. DataFrame Operations
4. Handle Missing Data
5. Descriptive Statistics
6. Data Visualization
7. Save Visualization
8. NumPy Numeric Analysis
9. Exit

Enter your choice:  3

1. Merge CSV
2. Split dataset
3. Back

Enter choice:  2

Part 1:

   id   name  age      city
0   1  Alice   25  New York

Part 2:

   id     name  age         city
1   2      Bob   30  Los Angeles
2   3  Charlie   35      Chicago

1. Merge CSV
2. Split dataset
3. Back

Enter choice:  3

===== DATA ANALYSIS & VISUALIZATION PROGRAM =====
1. Load Dataset
2. Explore Data
3. DataFrame Operations
4. Handle Missing Data
5. Descriptive Statistics
6. Data Visualization
7. Save Visualization
8. NumPy Numeric Analysis
9. Exit

Enter your choice:  4

1. Show missing rows
2. Fill with mean
3. Drop missing rows
4. Replace missing values
5. Back

Enter choice:  2

Missing numeric values filled.

1. Show missing rows
2. Fill with mean
3. Drop missing rows
4. Replace missing values
5. Back

Enter choice:  5

===== DATA ANALYSIS & VISUALIZATION PROGRAM =====
1. Load Dataset
2. Explore Data
3. DataFrame Operations
4. Handle Missing Data
5. Descriptive Statistics
6. Data Visualization
7. Save Visualization
8. NumPy Numeric Analysis
9. Exit

Enter your choice:  6

1. Bar Chart
2. Line Chart
3. Scatter Plot
4. Sales Pie Chart
5. Heatmap
6. Histogram
7. Stack Plot
8. Back

Enter choice:  2
Enter numeric column:  62

Chart error: '62'

1. Bar Chart
2. Line Chart
3. Scatter Plot
4. Sales Pie Chart
5. Heatmap
6. Histogram
7. Stack Plot
8. Back

Enter choice:  7
Enter numeric column:  2

Chart error: '2'

1. Bar Chart
2. Line Chart
3. Scatter Plot
4. Sales Pie Chart
5. Heatmap
6. Histogram
7. Stack Plot
8. Back

Enter choice:  8

===== DATA ANALYSIS & VISUALIZATION PROGRAM =====
1. Load Dataset
2. Explore Data
3. DataFrame Operations
4. Handle Missing Data
5. Descriptive Statistics
6. Data Visualization
7. Save Visualization
8. NumPy Numeric Analysis
9. Exit